### ISSUE TITLE
Identical attributions for all test images

### ISSUE THREAD

**Issue by avakanski** [d909b/cxplain#1]
I tried the CIFAR10 and MNIST example codes, and obtained the same attributions for all test images.  I used the provided CIFAR10 and MNIST example codes without any modifications.
Has anyone else had the same problem?
Thanks

**Comment by d909b** [comment]
Hi @avakanski, thank you for your comment! To keep the time spent in computations low, the CIFAR10 example notebook currently uses only 500 images from the CIFAR10 dataset. I suspect neither the explained nor the explaining model are therefore fully converged - please try using a larger number of samples. (The notebooks are primarily meant to show how to use the CXPlain API.)

**Comment by avakanski** [comment]
Hi Patrick, thank you very much for your quick reply. I run again the example code for MNIST images by using 50,000 images, but the attribution maps again are all identical. The accuracy of the prediction model was 95.7%, which is decent considering that the hyperparameters were not tuned.
I suspect that there is a bug in the codes that makes all attributions identical. I looked at the codes in more detail, and I wanted to ask you about the meaning of the following 2 parameters in build_explanation_model: num_indices and steps. I would appreciate if you could clarify the meaning of these two parameters. Thank you.

**Comment by d909b** [comment]
I had a quick look at the training of the explanation models in the CIFAR10 and MNIST notebooks (using verbose=2), and found that the CXPlain models converged at a very high loss due to a poor choice of hyperparameters. 

I updated the notebooks with hyperparameter settings that converge better - please have a look @avakanski, and do let me know if you are still experiencing any issues.

**Comment by avakanski** [comment]
Thank you Patrick, you were right, the models were not converging. Thank you for your help.
